# Run before merging a pull request and after changes reach main

name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  format:
    name: Format rust files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  lint:
    name: Lint all rust files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
        with:
          components: clippy
      - run: >-
          cargo clippy --all-targets --all-features --no-deps --
          -D warnings -D rustdoc::broken_intra_doc_links
          -W clippy::explicit_iter_loop -W clippy::explicit_into_iter_loop
          -W clippy::semicolon_if_nothing_returned -W clippy::doc_markdown
          -W clippy::manual_let_else

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
      - run: cargo test --workspace --all-features
      - run: cargo test --workspace --all-features --bench file-format-bench
      - run: git diff --exit-code -- benches/example.nu

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
        with:
          toolchain: "1.98"
      - run: cargo check --all-targets --all-features

  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build .#nufmt
      - run: nix flake check --accept-flake-config
